### ISSUE TITLE
Compile fails due to uppercase letters on stifDev_TAP_History.txt resource

### ISSUE THREAD

**Issue by chief27** [Stif-UK/StifDev_TAP#2]
**/app/src/main/res/raw/stifDev_TAP_History.txt** 

should be

 **/app/src/main/res/raw/stifdev_tap_history.txt**

**Comment by Stif-UK** [comment]
I fixed this when implemented, and have made numerous commits since, but strangely it keeps recurring (I created a new branch tonight and my first build failed for the same reason).
I'll have a proper look again and see if there's anything obviously wrong.

**Comment by chief27** [comment]
Resolved by: 

git mv stifDev_TAP_History.txt stifdev_tap_history.txt.new
mv stifdev_tap_history.txt.new stif_dev_tap_history.txt
git commit

Running the following should prevent it in the future:

git config core.ignorecase false
